add intermediates to trustStore
nuts-foundation/nuts-crypto pull request #113
Opened 2020-11-11 08:38 UTC by woutslakhorst

The truststore only contained roots. The Verify method did not take intermediates into account. For the nuts-auth module intermediates are required.

2020-11-11 08:45 UTC, woutslakhorst commented
nuts-registry will need an update

2020-11-11 09:08 UTC, reinkrul requested changes

2020-11-11 09:08 UTC, reinkrul commented on pkg/cert/truststore.go
> +		m.intermediates = append(m.roots, certificate)
If the unit tests don't fail on this one, you're missing a test case :-)

2020-11-12 19:09 UTC, reinkrul approved these changes

2020-11-13 10:36 UTC, merged