Add support for issuing TLS certificates
nuts-foundation/nuts-crypto pull request #53
Opened 2020-06-05 14:49 UTC by reinkrul

Fixes #52 

TODO:
 [ ] Tests

2020-06-08 14:51 UTC, woutslakhorst reviewed
That Qualifier thingy smells.... it's passed through several layers, just to change the filename...

2020-06-08 14:51 UTC, woutslakhorst commented on pkg/crypto.go
> +			NumDaysValid: 60,
magic num!

2020-06-11 06:48 UTC, reinkrul commented
> That Qualifier thingy smells.... it's passed through several layers, just to change the filename...

We need a way to distinguish different keys/certs for an entity (org/vendor). "Qualifier" is quite generic, an alternative would be creating an enum-esque structure with all types (Intermediate CA, TLS CA, TLS, etc) but that would limit extendability in the future. Although it would't be too bad to express our certificate tree in a type-safe manner in code, as to decrease the chance of bugs?

We currently just use "the organization/vendor's key", maybe we should be explicit about it anyways (which key to use)?

2020-06-11 07:18 UTC, woutslakhorst commented
The legalEntity + qualifier now form the `KeyIdentifier`. Maybe just call it that as an interface. This will also allow us to remove the term legalEntity from this layer. Since it doesn't really matter for the crypto if the identifier is derived from an organisation identifier.

2020-06-11 14:50 UTC, reinkrul commented
> The legalEntity + qualifier now form the `KeyIdentifier`. Maybe just call it that as an interface. This will also allow us to remove the term legalEntity from this layer. Since it doesn't really matter for the crypto if the identifier is derived from an organisation identifier.

Refactored (types.LegalEntity, types.Qualifier) parameters to types.KeyIdentifier. Got quite elaborate.

2020-06-15 07:49 UTC, woutslakhorst requested changes
Just the docs

2020-06-15 07:49 UTC, woutslakhorst commented on pkg/types/types.go
> +type KeyIdentifier interface {
docs on different funcs.

2020-06-15 13:05 UTC, reinkrul commented on pkg/types/types.go
> +type KeyIdentifier interface {
I'd expect codestyle to fail on this?

2020-06-16 14:47 UTC, woutslakhorst approved these changes

2020-06-16 14:48 UTC, woutslakhorst commented
Linter has been reconfigured, it default to python and shell..... not go

2020-06-17 08:08 UTC, merged